/cds/group/pcds/epics-dev/espov/jet_tracking/jet_tracking
/cds/group/pcds/epics-dev/espov/jet_tracking/jet_tracking
/cds/group/pcds/epics-dev/espov/jet_tracking/jet_tracking
/cds/group/pcds/epics-dev/espov/jet_tracking/jet_tracking
/cds/group/pcds/epics-dev/espov/jet_tracking/jet_tracking
/cds/group/pcds/epics-dev/espov/jet_tracking/jet_tracking
/cds/group/pcds/epics-dev/espov/jet_tracking/jet_tracking
/cds/group/pcds/epics-dev/espov/jet_tracking/jet_tracking
/cds/group/pcds/epics-dev/espov/jet_tracking/jet_tracking
/cds/group/pcds/epics-dev/espov/jet_tracking/jet_tracking
usage: jt_cal.py [-h] [--cfg CFG] [--run RUN]
usage: jt_cal.py [-h] [--cfg CFG] [--run RUN]
jt_cal.py: error: argument --run: expected one argument
usage: jt_cal.py [-h] [--cfg CFG] [--run RUN]
jt_cal.py: error: argument --run: expected one argument
usage: jt_cal.py [-h] [--cfg CFG] [--run RUN]
jt_cal.py: error: argument --run: expected one argument
usage: jt_cal.py [-h] [--cfg CFG] [--run RUN]
jt_cal.py: error: argument --run: expected one argument
usage: jt_cal.py [-h] [--cfg CFG] [--run RUN]
jt_cal.py: error: argument --run: expected one argument
usage: jt_cal.py [-h] [--cfg CFG] [--run RUN]
jt_cal.py: error: argument --run: expected one argument
usage: jt_cal.py [-h] [--cfg CFG] [--run RUN]
jt_cal.py: error: argument --run: expected one argument
usage: jt_cal.py [-h] [--cfg CFG] [--run RUN]
jt_cal.py: error: argument --run: expected one argument
usage: jt_cal.py [-h] [--cfg CFG] [--run RUN]
jt_cal.py: error: argument --run: expected one argument
jt_cal.py: error: argument --run: expected one argument
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[59930,1],3]
  Exit code:    2
--------------------------------------------------------------------------
